/**
 * Agent-scoped model selection shared by runtime entry points.
 * @module @deepseek-ai/dsh-agent/model-selection
 */

import type { Context } from '@deepseek-ai/cordis'
import {
  boundContextSummary,
  createUserMessage,
  type LlmCallConfig,
  type ReasoningEffortId,
} from '@deepseek-ai/dsh-llm'
import type { PreStepDecision } from './runtime-types.ts'

/**
 * Selection belonging to each Agent scope, keyed by the exact scope context the
 * selection was installed on. A Cordis accessor is declared in ONE process-wide
 * property table, so `modelSelection` can only ever be declared once however
 * many Agents run; the accessor that wins must therefore resolve its value from
 * the scope the read was made through rather than close over one Agent's.
 * Keying by the scope lets the entry die with that scope.
 */
const selectionByScope = new WeakMap<object, ModelSelectionRef>()

/**
 * Find the selection owning the scope a read was made through.
 *
 * A read arrives on the Agent's own scope or on any context extending it, so
 * the nearest registered ancestor is the owner. Absent means the reading scope
 * carries no Agent selection — never some other Agent's.
 * @param reading - context the `modelSelection` read went through.
 * @returns the owning selection, or undefined when this scope has none.
 */
function selectionOwnerOf(reading: object): ModelSelectionRef | undefined {
  let cursor: object | null = reading
  while (cursor !== null) {
    const found = selectionByScope.get(cursor)
    if (found !== undefined) return found
    cursor = Object.getPrototypeOf(cursor)
  }
  return undefined
}

/** Complete provider, model, and optional reasoning effort selected for one live Agent. */
export interface ModelSelection {
  /** Registered provider route. */
  provider: string
  /** Provider-owned model id. */
  model: string
  /** Adapter-owned reasoning effort, or provider/default behavior when absent. */
  reasoningEffort?: ReasoningEffortId
}

/** Mutable model selection plus the value captured for the current step. */
export interface ModelSelectionRef {
  /** Model selected for the next step that enters prompt assembly. */
  current: ModelSelection | undefined
  /** Selection captured when the current step entered prompt assembly. */
  assembled: ModelSelection | undefined
}

function sameRoute(left: ModelSelection, right: ModelSelection): boolean {
  return left.provider === right.provider && left.model === right.model
}

function routeLabel(route: ModelSelection, other: ModelSelection): string {
  return route.provider === other.provider ? route.model : `${route.provider}/${route.model}`
}

function modelSwitchNotice(previous: ModelSelection, selected: ModelSelection) {
  const from = routeLabel(previous, selected)
  const to = routeLabel(selected, previous)
  return createUserMessage({
    content: [{
      type: 'text' as const,
      text: `[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]`,
    }],
    source: {
      kind: 'plugin' as const,
      plugin: 'model-selection',
      form: 'notice' as const,
      summary: boundContextSummary(`${from} → ${to}`),
    },
  })
}

/**
 * Couple one mutable selection to Agent-scoped prompt assembly and request routing.
 * Prompt assembly snapshots the selected model before delegating, then applies
 * its provider/model pair and effort to request config so a
 * concurrent switch takes effect on a later step instead of splitting the two
 * surfaces. An absent selected effort clears any inherited effort, restoring
 * the selected model's provider/default behavior.
 *
 * A provider/model change appends a durable user-role notice to the next
 * admitted request. It compares the assembled selection with the latest
 * request header; effort-only changes and empty no-request decisions add no
 * notice. Failure before header persistence repeats the notice on the next
 * request.
 *
 * @param agentCtx - The selected Agent's scoped context.
 * @param selection - Mutable selection owned by the calling entry point.
 * @returns Disposer for all scoped waterfall listeners.
 */
export function installModelSelection(agentCtx: Context, selection: ModelSelectionRef): () => void {
  // DSH-FORK(fix): fork edit on an upstream-owned file. EXIT: upstream resolves
  // the accessor from the reading scope instead of closing over one selection.
  //
  // Declaring an accessor twice is a hard cordis error, and a resume or
  // reconnect re-enters setup on the same agent context before the previous
  // attempt unwound — hence the declaration is guarded. But the guarded
  // property table is on the ROOT reflect service, not per scope, so the guard
  // is true for every Agent after the first; returning early there left each of
  // them with no accessor of its own, and its `modelSelection` reads resolved
  // to whichever Agent installed first. Registering the selection per scope and
  // resolving it from the reading scope is what keeps two live Agents apart.
  selectionByScope.set(agentCtx, selection)
  if (!('modelSelection' in agentCtx)) {
    agentCtx.accessor('modelSelection', {
      get(this: Context) {
        return selectionOwnerOf(this)?.current
      },
    })
  }
  const disposeAssembly = agentCtx.on('system-prompt/assemble', async (_assembly, _context, next) => {
    const selected = selection.current
    const assembled = await next()
    selection.assembled = selected
    if (selected === undefined) return assembled
    return {
      ...assembled,
      variables: {
        ...assembled.variables,
        provider: selected.provider,
        model: selected.model,
      },
    }
  })
  const disposeRequest = agentCtx.on(
    'agent/request',
    async (_payload, next): Promise<LlmCallConfig> => {
      const resolved = await next()
      const selected = selection.assembled
      if (selected === undefined) return resolved
      const { reasoningEffort: _inheritedEffort, ...withoutInheritedEffort } = resolved
      return {
        ...withoutInheritedEffort,
        provider: selected.provider,
        model: selected.model,
        ...selected.reasoningEffort === undefined
          ? {}
          : { reasoningEffort: selected.reasoningEffort },
      }
    },
  )
  const disposeNotice = agentCtx.on(
    'agent/pre-step',
    async ({ agent, messages, signal, step }, next): Promise<PreStepDecision> => {
      const decision = await next()
      if (decision.kind === 'reject' || signal.aborted) return decision
      // The loop skips an empty first step and an emptied offered continuation.
      if (decision.messages.length === 0 && (step === 1 || messages.length > 0)) return decision
      const selected = selection.assembled
      const previous = agent.session.requestHeader()?.config
      if (selected === undefined || previous === undefined || sameRoute(selected, previous)) return decision
      return { ...decision, messages: [...decision.messages, modelSwitchNotice(previous, selected)] }
    },
    { prepend: true },
  )
  return () => {
    disposeAssembly()
    disposeRequest()
    disposeNotice()
    // Only the install that still owns the entry may drop it, so a re-entry
    // that replaced this selection keeps its own registration.
    if (selectionByScope.get(agentCtx) === selection) selectionByScope.delete(agentCtx)
  }
}


declare module '@deepseek-ai/cordis' {
  interface Context {
    /**
     * Live provider/model selection for the Agent owning this scoped context,
     * resolved through the entry point's precedence (picker switch, logged
     * request header, deployment default). Absent when no selection is
     * installed for this scope.
     */
    modelSelection?: ModelSelection | undefined
  }
}
