#!/usr/bin/env bash
# Install (or update) DeepSeek Harness EFAI so `dsh` runs from any directory.
#
#   curl -fsSL https://raw.githubusercontent.com/eefamilyai/Deepseek-Harness-EFAI/master/install.sh | bash
#
# Re-running this is how you update: it fast-forwards the checkout, reinstalls
# dependencies, and rebuilds. `dsh-update` is a shortcut for exactly that.
#
# What it touches:
#   ~/.deepseek-harness   the source checkout (override with DSH_INSTALL_DIR)
#   ~/.local/bin/dsh      the launcher on PATH (override with DSH_BIN_DIR)
#
# `$DSH_HOME` (~/.dsh) is the harness's own data home — settings, profiles,
# presets — and is deliberately NOT touched here, so reinstalling never
# disturbs your configuration.
set -euo pipefail

REPO_URL="${DSH_REPO_URL:-https://github.com/eefamilyai/Deepseek-Harness-EFAI.git}"
BRANCH="${DSH_BRANCH:-master}"
SRC_DIR="${DSH_INSTALL_DIR:-$HOME/.deepseek-harness}"
BIN_DIR="${DSH_BIN_DIR:-$HOME/.local/bin}"

say() { printf '[dsh-install] %s\n' "$*"; }
die() { printf '[dsh-install] ERROR: %s\n' "$*" >&2; exit 1; }

# ── Prerequisites ────────────────────────────────────────────────────────
command -v git >/dev/null 2>&1 || die "git is required. Install it, then re-run this."
command -v node >/dev/null 2>&1 || die "Node.js is required (^22.19 or >=24). See https://nodejs.org"

# The workspace declares node ^22.19 || >=24; a older runtime fails deep in the
# build with an unhelpful error, so check it here where the message can help.
node -e '
  const [maj, min] = process.versions.node.split(".").map(Number)
  const ok = maj >= 24 || (maj === 22 && min >= 19)
  if (!ok) {
    console.error(`Node ${process.versions.node} is too old; this needs ^22.19 or >=24.`)
    process.exit(1)
  }
' || die "Node version unsupported."

if ! command -v pnpm >/dev/null 2>&1; then
  say "pnpm not found — enabling it through corepack..."
  corepack enable >/dev/null 2>&1 || true
  corepack prepare pnpm@latest --activate >/dev/null 2>&1 || true
fi
command -v pnpm >/dev/null 2>&1 || die "pnpm is required. Install it with: npm install -g pnpm"

# ── Fetch or update the checkout ─────────────────────────────────────────
if [ -d "$SRC_DIR/.git" ]; then
  say "Updating $SRC_DIR ..."
  git -C "$SRC_DIR" remote set-url origin "$REPO_URL"
  git -C "$SRC_DIR" fetch --quiet origin "$BRANCH"
  # A local edit in the install checkout is not worth silently discarding, but
  # it also must not wedge the update, so say so and leave the tree alone.
  if ! git -C "$SRC_DIR" diff --quiet || ! git -C "$SRC_DIR" diff --cached --quiet; then
    die "$SRC_DIR has uncommitted changes. Commit, stash, or remove them, then re-run."
  fi
  git -C "$SRC_DIR" checkout --quiet -B "$BRANCH" "origin/$BRANCH"
else
  [ -e "$SRC_DIR" ] && die "$SRC_DIR exists but is not a git checkout. Move it aside, then re-run."
  say "Cloning $REPO_URL into $SRC_DIR ..."
  git clone --quiet --branch "$BRANCH" "$REPO_URL" "$SRC_DIR"
fi

say "Installed revision: $(git -C "$SRC_DIR" rev-parse --short HEAD)"

# ── Build ────────────────────────────────────────────────────────────────
cd "$SRC_DIR"
say "Installing dependencies (this is the slow part on a fresh machine)..."
pnpm install --frozen-lockfile || pnpm install
say "Building..."
pnpm run build

[ -f apps/cli/lib/bin.js ] || die "the build finished but apps/cli/lib/bin.js is missing."

# ── Bundled Python, best effort ──────────────────────────────────────────
# The kernel tool and the Kiln providers want their own interpreter. start.sh
# provisions this on every web-UI launch; doing it once here keeps the `dsh`
# launcher fast. A failure here never fails the install — the affected tools
# report their own unavailability.
RUNTIME_DIR="$SRC_DIR/python/kiln/runtime"
if [ -d "$RUNTIME_DIR" ]; then
  if ! command -v uv >/dev/null 2>&1; then
    say "Installing uv for the bundled Python runtime..."
    curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null 2>&1 || true
    export PATH="$HOME/.local/bin:$PATH"
  fi
  if command -v uv >/dev/null 2>&1; then
    say "Provisioning the bundled Python runtime..."
    # `--frozen` honors the committed uv.lock. Without it uv rewrites the lock,
    # which leaves this checkout dirty and makes the NEXT update refuse to run.
    if ! ( cd "$RUNTIME_DIR" && uv sync --frozen ) >/dev/null 2>&1; then
      ( cd "$RUNTIME_DIR" && uv sync ) >/dev/null 2>&1 \
        || say "WARNING: uv sync failed; the kernel falls back to a system Python."
    fi
    # Whatever the fallback did to tracked files, the install checkout has to
    # end clean or dsh-update stops working.
    git -C "$SRC_DIR" checkout --quiet -- python/kiln/runtime/uv.lock 2>/dev/null || true
  fi
fi

# ── Launchers on PATH ────────────────────────────────────────────────────
mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/dsh" <<LAUNCHER
#!/usr/bin/env bash
# Generated by install.sh — re-run the installer to regenerate.
set -euo pipefail
SRC="$SRC_DIR"
# The kernel starts in the directory you invoked dsh from, not the checkout.
export DSH_KERNEL_CWD="\${DSH_KERNEL_CWD:-\$PWD}"
VENV_PY="\$SRC/python/kiln/runtime/.venv/bin/python"
if [ -x "\$VENV_PY" ]; then export DSH_KERNEL_PYTHON="\${DSH_KERNEL_PYTHON:-\$VENV_PY}"; fi
exec node "\$SRC/apps/cli/lib/bin.js" "\$@"
LAUNCHER
chmod +x "$BIN_DIR/dsh"

cat > "$BIN_DIR/dsh-update" <<UPDATER
#!/usr/bin/env bash
# Generated by install.sh — pulls the latest and rebuilds.
exec bash "$SRC_DIR/install.sh"
UPDATER
chmod +x "$BIN_DIR/dsh-update"

say "Installed: $BIN_DIR/dsh and $BIN_DIR/dsh-update"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    say ""
    say "$BIN_DIR is not on your PATH. Add this to your shell profile:"
    say "    export PATH=\"$BIN_DIR:\$PATH\""
    ;;
esac

say ""
say "Done. Try:  dsh web        (the browser UI)"
say "            dsh --help     (everything else)"
say "            dsh-update     (pull the latest and rebuild)"
