// Regenerate the mod layer from the current working tree.
//
// Usage:
//   node local-overlay/rebuild.mjs            # rewrite patches/ and INVENTORY.md
//   node local-overlay/rebuild.mjs --check    # report drift, write nothing, exit 1 on drift
//
// The patch set is a pure function of the recorded base commit and the working
// tree, so it is regenerated rather than hand-edited. A path no rule claims is
// reported and fails the run: it is either a missing rule, or an edit that
// belongs in a fork-owned file.
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  changedPaths, classify, diffFor, generatedFor, groupFor,
  overlayDir, patchDir, readBase, readRules,
} from './lib.mjs'

const checkOnly = process.argv.includes('--check')

/**
 * Write a file with LF endings, so a Windows checkout and a POSIX checkout
 * produce byte-identical patches.
 * @param path - destination.
 * @param text - contents.
 */
function writeText(path, text) {
  writeFileSync(path, text.replace(/\r\n/g, '\n'), 'utf8')
}

/**
 * Read a file as UTF-8.
 * @param path - source.
 * @returns the contents, or null when the file is absent.
 */
function readText(path) {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    return null
  }
}

/** Render the manifest from the classified paths and the patch plans. */
function buildInventory(state) {
  const total = state.plans.reduce((sum, plan) => sum + plan.paths.length, 0)
  const lines = [
    '# Local Overlay Manifest',
    '',
    `Upstream base: \`${state.base}\``,
    '',
    'Generated by `node local-overlay/rebuild.mjs` — do not edit by hand.',
    '',
    'Every file listed under **Patches** is an upstream-owned file this fork modifies.',
    'That list is the whole merge cost of an upstream update, and the patches are the',
    'fork\'s side of it: each one applies onto the base commit above.',
    '',
    `Tier-2 files: **${total}** in **${state.plans.length}** patch(es).`,
    '',
    '## Patches',
    '',
  ]
  for (const plan of state.plans) {
    lines.push(`### \`patches/${plan.name}.patch\` — ${plan.paths.length} file(s)`)
    lines.push('')
    for (const path of [...plan.paths].sort()) lines.push(`- \`${path}\``)
    lines.push('')
  }
  lines.push('## Regenerated, never patched')
  lines.push('')
  lines.push('A generator owns these. On an upstream update take upstream\'s side wholesale, then run the command.')
  lines.push('')
  lines.push('| File | Regenerate with |')
  lines.push('| --- | --- |')
  for (const entry of state.rules.generated) lines.push(`| \`${entry.path}\` | \`${entry.regenerate}\` |`)
  lines.push('')
  lines.push('## Fork-owned, no patch needed')
  lines.push('')
  lines.push(`These ${state.tier1.length} paths do not exist upstream, so no patch covers them and none can conflict.`)
  lines.push('')
  for (const path of [...state.tier1].sort()) lines.push(`- \`${path}\``)
  // The last element is an empty separator line; drop it so the file ends with
  // exactly one newline and no blank line at EOF.
  while (lines.at(-1) === '') lines.pop()
  return `${lines.join('\n')}\n`
}

const base = readBase()
const rules = readRules()
const records = changedPaths(base)
const { tier1, tier2, generated, unclaimed } = classify(records, rules)

if (unclaimed.length > 0) {
  console.error('Paths no rule claims — add a patchGroup in rules.json, or move the edit to a fork-owned file:')
  for (const record of unclaimed) console.error(`  ${record.status}  ${record.path}`)
  process.exitCode = 1
}

// Collect each group's paths in rules.json declaration order, so the patch set
// is stable across runs and a review sees only real changes.
const byGroup = new Map(rules.patchGroups.map(group => [group.name, []]))
for (const record of tier2) {
  const name = groupFor(record.path, rules)
  if (name !== null) byGroup.get(name).push(record.path)
}

const plans = []
for (const [name, paths] of byGroup) {
  if (paths.length === 0) continue
  const body = diffFor(base, paths)
  if (body.trim() === '') continue
  plans.push({ name, paths, body })
}

const existing = readdirSync(patchDir).filter(name => name.endsWith('.patch'))
const produced = new Set(plans.map(plan => `${plan.name}.patch`))
let drift = 0

if (!checkOnly) mkdirSync(patchDir, { recursive: true })

for (const plan of plans) {
  const file = `${plan.name}.patch`
  const target = join(patchDir, file)
  if (readText(target) === plan.body) continue
  drift++
  if (checkOnly) {
    console.error(`DRIFT ${file} (${plan.paths.length} file(s)) — run: node local-overlay/rebuild.mjs`)
    continue
  }
  writeText(target, plan.body)
  console.log(`WROTE ${file}  ${plan.paths.length} file(s)`)
}

// A patch no rule produces is spent: upstream landed the change, or the fork
// moved the edit into a fork-owned file. Either way it must not linger.
for (const file of existing) {
  if (produced.has(file)) continue
  drift++
  if (checkOnly) {
    console.error(`STALE ${file} — no rule produces it; run: node local-overlay/rebuild.mjs`)
    continue
  }
  rmSync(join(patchDir, file))
  console.log(`REMOVED ${file}`)
}

const inventoryPath = join(overlayDir, 'INVENTORY.md')
const inventory = buildInventory({ base, rules, plans, tier1 })
if (readText(inventoryPath) !== inventory) {
  drift++
  if (checkOnly) console.error('DRIFT INVENTORY.md — run: node local-overlay/rebuild.mjs')
  else {
    writeText(inventoryPath, inventory)
    console.log('WROTE INVENTORY.md')
  }
}

if (checkOnly) {
  if (drift === 0) {
    console.log(`local-overlay is current: ${plans.length} patch(es), ${tier2.length} Tier-2 file(s), base ${base.slice(0, 10)}`)
  } else {
    process.exitCode = 1
  }
} else {
  console.log(`Rebuilt ${plans.length} patch(es) covering ${tier2.length} Tier-2 file(s) against base ${base.slice(0, 10)}.`)
  console.log(`Tier 1 (fork-owned, no patch needed): ${tier1.length} path(s).`)
  for (const record of generated) {
    console.log(`GENERATED (never patched) ${record.path}  ->  ${generatedFor(record.path, rules).regenerate}`)
  }
}
